export const fontfam = [
    "Abadi MT", "Minion Web", "Agency FB", "Aharoni Bold", "Aldhabi", "Algerian", "Almanac MT",
    "American Uncial", "Andale Mono", "Andalus", "Andy", "AngsanaUPC", "Angsana New", "Aparajita",
    "ArabicTransparent","ArabicTypesetting", "Arial", "Arial Black", "Arial Narrow", "Arial Narrow Special",
    "Arial Rounded MT", "Arial Special", "Arial Unicode MS", "Augsburger Initials", "Avenir Next LT Pro",
    "Bahnschrift", "Baskerville Old Face", "Batang & BatangChe", "Bauhaus 93",
    "Beesknees ITC", "Bell MT", "Bembo", "Berlin Sans FB", "Bernard MT Condensed",
    "Bickley Script", "Biome", "BIZ UDGothic", "BIZ UDMincho Medium", "Blackadder ITC",
    "Bodoni MT", "Bodoni MT Condensed", "Bon Apetit MT", "Bookman Old Style", "BookshelfSymbol",
    "Book Antiqua", "Bradley Hand ITC", "Braggadocio", "BriemScript", "Britannic Bold",
    "Broadway", "BrowalliaUPC", "Browallia New", "Brush Script MT",
    "Calibri",
    "Californian FB",
    "Calisto MT",
    "Cambria",
    "Cambria Math",
    "Candara",
    "Cariadings",
    "Castellar",
    "Cavolini",
    "Centaur",
    "Century",
    "Century Gothic",
    "Century Schoolbook",
    "Chiller",
    "Colonna MT",
    "ComicSans MS",
    "Consolas",
    "Constantia",
    "Contemporary Brush",
    "Cooper Black",
    "Copperplate Gothic",
    "Corbel",
    "CordiaUPC",
    "Cordia New",
    "Courier New",
    "Curlz MT",
    "Dante",
    "DaunPenh",
    "David",
    "Daytona",
    "Desdemona",
    "DFKai-SB",
    "DilleniaUPC",
    "Directions MT",
    "DokChampa",
    "Dotum & DotumChe",
    "Ebrima",
    "Eckmann",
    "Edda",
    "Edwardian Script ITC",
    "Elephant",
    "Engravers MT",
    "Enviro",
    "Eras ITC",
    "Estrangelo Edessa",
    "EucrosiaUPC",
    "Euphemia",
    "Eurostile",
    "FangSong",
    "FelixTitling",
    "Fine Hand",
    "Fixed Miriam Transparent",
    "Flexure",
    "Footlight MT",
    "Forte",
    "Franklin Gothic",
    "Franklin Gothic Medium",
    "FrankRuehl",
    "FreesiaUPC",
    "FreestyleScript",
    "French Script MT",
    "Futura",
    "Gabriola",
    "Gadugi",
    "Garamond",
    "Garamond MT",
    "Gautami",
    "Georgia",
    "Georgia Ref",
    "Gigi",
    "Gill Sans MT",
    "Gill Sans MT Condensed",
    "Gisha",
    "Gloucester",
    "Goudy Old Style",
    "Goudy Stout",
    "Gradl",
    "Grotesque",
    "Gulim & GulimChe",
    "Gungsuh & GungsuhChe",
    "Hadassah Friedlaender",
    "Haettenschweiler",
    "Harlow Solid Italic",
    "Harrington",
    "HGGothicE",
    "HGMinchoE",
    "HGSoeiKakugothicUB",
    "High Tower Text",
    "Holidays MT",
    "HoloLens MDL2 Assets",
    "Impact",
    "Imprint MTShadow",
    "Informal Roman",
    "IrisUPC",
    "Iskoola Pota",
    "JasmineUPC",
    "JavaneseText",
    "Jokerman",
    "JuiceITC",
    "KaiTi",
    "Kalinga",
    "Kartika",
    "Keystrokes MT",
    "Khmer UI",
    "Kigelia",
    "Kino MT",
    "KodchiangUPC",
    "Kokila",
    "Kristen ITC",
    "Kunstler Script",
    "Lao UI",
    "Latha",
    "LCD",
    "Leelawadee",
    "Levenim MT",
    "LilyUPC",
    "Lucida Blackletter",
    "Lucida Bright",
    "Lucida Bright Math",
    "Lucida Calligraphy",
    "Lucida Console",
    "Lucida Fax",
    "Lucida Handwriting",
    "LucidaSans",
    "LucidaSans Typewriter",
    "LucidaSans Unicode",
    "Magneto",
    "Maiandra GD",
    "Malgun Gothic",
    "Mangal",
    "Map Symbols",
    "Marlett",
    "MatisseITC",
    "Matura MTScript Capitals",
    "McZee",
    "Mead Bold",
    "Meiryo",
    "Mercurius Script MT Bold",
    "Microsoft GothicNeo",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft JhengHei UI",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "MicrosoftSans Serif",
    "MicrosoftTai Le",
    "Microsoft Uighur",
    "Microsoft YaHei",
    "Microsoft YaHei UI",
    "Microsoft Yi Baiti",
    "MingLiU",
    "MingLiU-ExtB",
    "MingLiU_HKSCS",
    "MingLiU_HKSCS-ExtB",
    "Minion Web",
    "Miriam",
    "Miriam Fixed",
    "Mistral",
    "Modern Love",
    "Modern No. 20",
    "Mongolian Baiti",
    "Monotype.com",
    "Monotype Corsiva",
    "MonotypeSorts",
    "MoolBoran",
    "MS Gothic",
    "MS LineDraw",
    "MS Mincho",
    "MS Outlook",
    "MS PGothic",
    "MS PMincho",
    "MS Reference",
    "MS UI Gothic",
    "MTExtra",
    "MV Boli",
    "Myanmar Text",
    "Narkisim",
    "News Gothic MT",
    "New Caledonia",
    "Niagara",
    "Nirmala UI",
    "Nyala",
    "OCR-B-Digits",
    "OCRB",
    "OCR A Extended",
    "Old English Text MT",
    "Onyx",
    "PalaceScript MT",
    "Palatino Linotype",
    "Papyrus",
    "Parade",
    "Parchment",
    "Parties MT",
    "Peignot Medium",
    "Pepita MT",
    "Perpetua",
    "PerpetuaTitling MT",
    "Placard Condensed",
    "Plantagenet Cherokee",
    "Playbill",
    "PMingLiU",
    "PMingLiU-ExtB",
    "Poor Richard",
    "Posterama",
    "Pristina",
    "QuireSans",
    "Raavi",
    "RageItalic",
    "Ransom",
    "Ravie",
    "RefSpecialty",
    "Rockwell",
    "Rockwell Nova",
    "Rod",
    "Runic MT Condensed",
    "Sabon Next LT",
    "Sagona",
    "Sakkal Majalla",
    "Script MT Bold",
    "Segoe Chess",
    "Segoe Print",
    "SegoeScript",
    "Segoe UI",
    "Segoe UISymbol",
    "Selawik",
    "Shonar Bangla",
    "Showcard Gothic",
    "Shruti",
    "Signs MT",
    "SimHei",
    "Simplified ArabicFixed",
    "SimSun",
    "SimSun-ExtB",
    "Sitka",
    "NSimSun",
    "Snap ITC",
    "Sports MT",
    "STCaiyun",
    "Stencil",
    "STFangsong",
    "STHupo",
    "STKaiti",
    "Stop",
    "STXihei",
    "STXingkai",
    "STXinwei",
    "STZhongsong",
    "Sylfaen",
    "Symbol",
    "Tahoma",
    "Tempo Grunge",
    "Tempus Sans ITC",
    "Temp Installer Font",
    "The Hand",
    "TheSerif Hand",
    "Times New Roman",
    "Times New Roman Special",
    "Tisa OffcSerif Pro",
    "Traditional Arabic",
    "Transport MT",
    "Trebuchet MS",
    "Tunga",
    "Tw Cen MT",
    "Univers",
    "Urdu Typesetting",
    "Utsaah",
    "Vacation MT",
    "Vani",
    "Verdana",
    "Verdana Ref",
    "Vijaya",
    "Viner Hand ITC",
    "Vivaldi",
    "Vixar ASCI",
    "Vladimir Script",
    "Vrinda",
    "Walbaum",
    "Webdings",
    "Westminster",
    "WideLatin",
]